{
programs.fastfetch = {
    enable = true;
    settings = {
	"$schema"= "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json";
    "logo"= {
        "padding"= {
            "top"= 2;
        };
    };
    "modules"= [
#        "title"
#        "separator"
        "os"
        "host"
#        "bios"
        "bootmgr"
#        "board"
#        "chassis"
        "kernel"
        "initsystem"
        "uptime"
        "loadavg"
        "processes"
        "packages"
        "shell"
        "editor"
#        "display"
#        "brightness"
#        "monitor"
        "lm"
        "de"
        "wm"
        "wmtheme"
        "theme"
        "icons"
        "font"
        "cursor"
        "wallpaper"
        "terminal"
        "terminalfont"
#        "terminalsize"
#        "terminaltheme"
            "cpu" 
#        "cpucache" 
#        "cpuusage" 
            "gpu" 
        "memory" 
        "physicalmemory" 
        "swap" 
        "disk" 
        "btrfs" 
        "zpool" 
            "battery" 
        "poweradapter" 
#        "player" 
#        "media" 
#            "publicip" 
 #           "localip" 
            "showIpv6" 
            "showMac" 
            "showSpeed" 
            "showMtu" 
            "showLoop" 
            "showFlags" 
            "showAllIps" 
        "dns" 
        "wifi" 
        "datetime" 
        "locale" 
        "vulkan" 
        "opengl" 
        "opencl" 
        "users" 
        "bluetooth" 
        "bluetoothradio" 
        "sound" 
        "camera" 
        "gamepad" 
        "mouse" 
        "keyboard" 
        "netio" 
        "diskio" 
            "physicaldisk" 
        "tpm" 
        "version" 
        "break" 
    ];


};
};
}
